version: 2.1

jobs:
  integration_test_with_downloaded_playwright_driver_chromium:
    docker:
      - image: mcr.microsoft.com/playwright:bionic
    steps:
      - checkout
      - run:
          name: Install Ruby 2.7.2 via RVM
          command: |
            count=0
            until gpg --keyserver hkp://ipv4.pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
            do
                count=$((count+1)); sleep 10;
                if [ $count -gt 2 ]; then
                    echo "Unable to receive GPG keys, FAILING";
                    exit 1;
                fi;
                echo "Network error: Unable to receive GPG keys. Will attempt again ($count/3)";
            done;

            curl -sSL https://get.rvm.io | bash -s stable --ruby
            source /usr/local/rvm/scripts/rvm
            rvm install 2.7.2
            rvm use 2.7.2
            echo . $(rvm 2.7.2 do rvm env --path) >> $BASH_ENV
            gem install bundler:2.2.3 && bundle install
      - run:
          name: Setup playwright driver
          command: |
            apt-get install -y unzip wget
            wget -O driver.zip https://playwright.azureedge.net/builds/driver/next/playwright-$(cat development/CLI_VERSION)-linux.zip
            unzip driver.zip && rm driver.zip
            ./playwright.sh install
      - run:
          command: bundle exec ruby development/generate_api.rb
      - run:
          name: RSpec
          command: |
            DEBUG=1 PLAYWRIGHT_CLI_EXECUTABLE_PATH=./playwright.sh \
            xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- bundle exec rspec spec/integration \
            --format RspecJunitFormatter \
            --out test_results/rspec.xml \
            --format documentation \
            --profile 10

  integration_test_with_downloaded_playwright_driver_webkit:
    docker:
      - image: mcr.microsoft.com/playwright:bionic
    steps:
      - checkout
      - run:
          name: Install Ruby 2.7.2 via RVM
          command: |
            count=0
            until gpg --keyserver hkp://ipv4.pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
            do
                count=$((count+1)); sleep 10;
                if [ $count -gt 2 ]; then
                    echo "Unable to receive GPG keys, FAILING";
                    exit 1;
                fi;
                echo "Network error: Unable to receive GPG keys. Will attempt again ($count/3)";
            done;

            curl -sSL https://get.rvm.io | bash -s stable --ruby
            source /usr/local/rvm/scripts/rvm
            rvm install 2.7.2
            rvm use 2.7.2
            echo . $(rvm 2.7.2 do rvm env --path) >> $BASH_ENV
            gem install bundler:2.2.3 && bundle install
      - run:
          name: Setup playwright driver
          command: |
            apt-get install -y unzip wget
            wget -O driver.zip https://playwright.azureedge.net/builds/driver/next/playwright-$(cat development/CLI_VERSION)-linux.zip
            unzip driver.zip && rm driver.zip
            ./playwright.sh install
      - run:
          command: bundle exec ruby development/generate_api.rb
      - run:
          name: RSpec
          command: |
            BROWSER=webkit DEBUG=1 PLAYWRIGHT_CLI_EXECUTABLE_PATH=./playwright.sh \
            xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- bundle exec rspec spec/integration \
            --format RspecJunitFormatter \
            --out test_results/rspec.xml \
            --format documentation \
            --profile 10

workflows:
  ci:
    jobs:
      - integration_test_with_downloaded_playwright_driver_chromium
      - integration_test_with_downloaded_playwright_driver_webkit
