name: Check

on: [pull_request]

jobs:
  unit_test:
    name: documents updated
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true
    - uses: actions/setup-node@v1
      with:
        node-version: 14
    - name: Download playwright driver
      run: |
        wget -O driver.zip https://playwright.azureedge.net/builds/driver/next/playwright-$(cat development/CLI_VERSION)-linux.zip
        unzip driver.zip && rm driver.zip
    - name: re-generate codes
      run: |
        ./playwright.sh print-api-json | jq . > development/api.json
        find docs -name "*.md" | xargs rm
        bundle exec ruby development/generate_api.rb
    - name: Check if api.json is updated
      run: git diff --exit-code development/api.json
    - name: Check if docs/ is updated
      run: |
        git diff --exit-code docs
        git add -N docs
        git diff --exit-code docs
