name: RSpec

on: [pull_request]

jobs:
  unit_test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
        bundler-cache: true
    - run: |
        rm -rf spec/integration
        bundle exec rspec
